name: check
on: push
jobs:
  lint:
    name: lint
    runs-on: macOS-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          fetch-depth: 1
      - name: Install remark
        run: |
          npm install remark-cli
          npm install remark-validate-links
          npm install remark-lint
          npm install remark-lint-no-dead-urls
      - name: remark
        run: |
          ./node_modules/.bin/remark .
      - name: validate-links
        run: |
          ./node_modules/.bin/remark -u validate-links  .
      - name: remark-lint
        run: |
          ./node_modules/.bin/remark -u remark-lint  .

